fix action test and lint

diff --git a/.github/workflows/test-and-lint.yml b/.github/workflows/test-and-lint.yml
--- a/.github/workflows/test-and-lint.yml
+++ b/.github/workflows/test-and-lint.yml
@@ -22,11 +22,14 @@ jobs:
         id: get-changes
         run: |
           echo "Detecting changed folders..."
-          CHANGED_FOLDERS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^contrib/' | cut -d'/' -f2 | sort | uniq)
+          BEFORE_COMMIT=${{ github.event.before }}
+          if ! git cat-file -e $BEFORE_COMMIT 2>/dev/null; then
+            echo "Invalid 'before' commit. Using the default branch as the base."
+            BEFORE_COMMIT=$(git rev-parse origin/${{ github.event.repository.default_branch }})
+          fi
+          CHANGED_FOLDERS=$(git diff --name-only $BEFORE_COMMIT ${{ github.sha }} | grep '^contrib/' | cut -d'/' -f2 | sort | uniq)
           echo "Changed folders: $CHANGED_FOLDERS"
-          echo "::set-output name=folders::[$(echo $CHANGED_FOLDERS | jq -R -s -c 'split("\n") | map(select(. != ""))')]"
-#        run: |
-#          echo "::set-output name=folders::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^contrib/' | cut -d'/' -f2 | sort | uniq | jq -R -s -c 'split("\n")[:-1]')"
+          echo "::set-output name=folders::[$(echo $CHANGED_FOLDERS | jq -R -s -c 'split(\"\\n\") | map(select(. != \"\"))')]"
 
   test-and-lint:
     runs-on: ubuntu-latest
